#!/usr/bin/env bash
#
# generate-schema.sh - Generate schema files from a running database
#
# Usage:
#   ./scripts/generate-schema.sh --from-db mysql://user:pass@localhost:3306/dbname
#   ./scripts/generate-schema.sh --from-db mysql://user:pass@localhost:3306/dbname --output infra/mysql/schema
#
# This script:
#   1. Connects to the specified database
#   2. Dumps table structures, triggers, procedures, and views
#   3. Writes individual files to schema/tables/, schema/triggers/, etc.
#   4. Generates a combined baseline.sql
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Defaults
OUTPUT_DIR="infra/mysql/schema"
DB_URL=""

usage() {
    echo "Usage: $0 --from-db <mysql-url> [--output <dir>]"
    echo ""
    echo "Options:"
    echo "  --from-db   MySQL connection URL (mysql://user:pass@host:port/database)"
    echo "  --output    Output directory (default: infra/mysql/schema)"
    echo ""
    echo "Examples:"
    echo "  $0 --from-db mysql://root:secret@localhost:3306/myapp"
    echo "  $0 --from-db mysql://root:secret@localhost:3306/myapp --output ./schema"
    exit 1
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --from-db)
            DB_URL="$2"
            shift 2
            ;;
        --output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

if [[ -z "$DB_URL" ]]; then
    log_error "Missing required --from-db argument"
    usage
fi

# Parse MySQL URL: mysql://user:pass@host:port/database
if [[ "$DB_URL" =~ mysql://([^:]+):([^@]+)@([^:]+):([0-9]+)/(.+) ]]; then
    DB_USER="${BASH_REMATCH[1]}"
    DB_PASS="${BASH_REMATCH[2]}"
    DB_HOST="${BASH_REMATCH[3]}"
    DB_PORT="${BASH_REMATCH[4]}"
    DB_NAME="${BASH_REMATCH[5]}"
elif [[ "$DB_URL" =~ mysql://([^:]+):([^@]+)@([^/]+)/(.+) ]]; then
    DB_USER="${BASH_REMATCH[1]}"
    DB_PASS="${BASH_REMATCH[2]}"
    DB_HOST="${BASH_REMATCH[3]}"
    DB_PORT="3306"
    DB_NAME="${BASH_REMATCH[4]}"
else
    log_error "Invalid MySQL URL format. Expected: mysql://user:pass@host:port/database"
    exit 1
fi

# MySQL command helper
mysql_cmd() {
    mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -N -B "$@"
}

mysqldump_cmd() {
    mysqldump -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" "$@"
}

log_info "Connecting to $DB_HOST:$DB_PORT/$DB_NAME..."

# Test connection
if ! mysql_cmd -e "SELECT 1" > /dev/null 2>&1; then
    log_error "Failed to connect to database"
    exit 1
fi

log_success "Connected to database"

# Create output directories
mkdir -p "$OUTPUT_DIR"/{tables,triggers,procedures,views}

# Get latest migration version from flyway_schema_history
BASELINE_VERSION=$(mysql_cmd -e "SELECT COALESCE(MAX(version), '000') FROM flyway_schema_history WHERE success = 1" 2>/dev/null || echo "001")
log_info "Baseline version: $BASELINE_VERSION"

# -----------------------------------------------------------------------------
# Dump Tables
# -----------------------------------------------------------------------------
log_info "Dumping tables..."

TABLES=$(mysql_cmd -e "SHOW TABLES")
for TABLE in $TABLES; do
    # Skip Flyway metadata table
    if [[ "$TABLE" == "flyway_schema_history" ]]; then
        continue
    fi

    log_info "  - $TABLE"

    # Get CREATE TABLE statement
    CREATE_STMT=$(mysql_cmd -e "SHOW CREATE TABLE \`$TABLE\`" | cut -f2-)

    cat > "$OUTPUT_DIR/tables/${TABLE}.sql" << EOF
-- $TABLE table
-- Generated by: generate-schema.sh

$CREATE_STMT;
EOF
done

# -----------------------------------------------------------------------------
# Dump Triggers
# -----------------------------------------------------------------------------
log_info "Dumping triggers..."

TRIGGERS=$(mysql_cmd -e "SELECT TRIGGER_NAME FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA = '$DB_NAME'")
for TRIGGER in $TRIGGERS; do
    log_info "  - $TRIGGER"

    # Get CREATE TRIGGER statement
    CREATE_STMT=$(mysql_cmd -e "SHOW CREATE TRIGGER \`$TRIGGER\`" | cut -f3-)

    cat > "$OUTPUT_DIR/triggers/${TRIGGER}.sql" << EOF
-- $TRIGGER trigger
-- Generated by: generate-schema.sh

DELIMITER //
$CREATE_STMT//
DELIMITER ;
EOF
done

if [[ -z "$TRIGGERS" ]]; then
    log_info "  (none found)"
fi

# -----------------------------------------------------------------------------
# Dump Stored Procedures
# -----------------------------------------------------------------------------
log_info "Dumping stored procedures..."

PROCEDURES=$(mysql_cmd -e "SELECT ROUTINE_NAME FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = '$DB_NAME' AND ROUTINE_TYPE = 'PROCEDURE'")
for PROC in $PROCEDURES; do
    log_info "  - $PROC"

    # Get CREATE PROCEDURE statement
    CREATE_STMT=$(mysql_cmd -e "SHOW CREATE PROCEDURE \`$PROC\`" | cut -f3-)

    cat > "$OUTPUT_DIR/procedures/${PROC}.sql" << EOF
-- $PROC procedure
-- Generated by: generate-schema.sh

DELIMITER //
$CREATE_STMT//
DELIMITER ;
EOF
done

if [[ -z "$PROCEDURES" ]]; then
    log_info "  (none found)"
fi

# -----------------------------------------------------------------------------
# Dump Views
# -----------------------------------------------------------------------------
log_info "Dumping views..."

VIEWS=$(mysql_cmd -e "SELECT TABLE_NAME FROM information_schema.VIEWS WHERE TABLE_SCHEMA = '$DB_NAME'")
for VIEW in $VIEWS; do
    log_info "  - $VIEW"

    # Get CREATE VIEW statement
    CREATE_STMT=$(mysql_cmd -e "SHOW CREATE VIEW \`$VIEW\`" | cut -f2-)

    cat > "$OUTPUT_DIR/views/${VIEW}.sql" << EOF
-- $VIEW view
-- Generated by: generate-schema.sh

$CREATE_STMT;
EOF
done

if [[ -z "$VIEWS" ]]; then
    log_info "  (none found)"
fi

# -----------------------------------------------------------------------------
# Generate Combined Baseline
# -----------------------------------------------------------------------------
log_info "Generating baseline.sql..."

cat > "$OUTPUT_DIR/baseline.sql" << HEADER
-- =============================================================================
-- DATABASE BASELINE SCHEMA
-- =============================================================================
-- This file contains the complete database schema for bootstrapping new
-- environments. It represents the state after all migrations have been applied.
--
-- Baseline version: $BASELINE_VERSION
-- Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
-- Generated by: generate-schema.sh
--
-- Usage:
--   mysql -u root -p database_name < baseline.sql
--   flyway -baselineVersion=$BASELINE_VERSION baseline
--
-- DO NOT EDIT MANUALLY - Regenerate using: ./scripts/generate-schema.sh
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------------------------
-- TABLES
-- -----------------------------------------------------------------------------

HEADER

# Append all table definitions
for TABLE_FILE in "$OUTPUT_DIR"/tables/*.sql; do
    if [[ -f "$TABLE_FILE" ]]; then
        echo "" >> "$OUTPUT_DIR/baseline.sql"
        cat "$TABLE_FILE" >> "$OUTPUT_DIR/baseline.sql"
        echo "" >> "$OUTPUT_DIR/baseline.sql"
    fi
done

# Append triggers section
cat >> "$OUTPUT_DIR/baseline.sql" << 'TRIGGERS_HEADER'

-- -----------------------------------------------------------------------------
-- TRIGGERS
-- -----------------------------------------------------------------------------

TRIGGERS_HEADER

for TRIGGER_FILE in "$OUTPUT_DIR"/triggers/*.sql; do
    if [[ -f "$TRIGGER_FILE" ]]; then
        cat "$TRIGGER_FILE" >> "$OUTPUT_DIR/baseline.sql"
        echo "" >> "$OUTPUT_DIR/baseline.sql"
    fi
done

if [[ ! -f "$OUTPUT_DIR"/triggers/*.sql ]]; then
    echo "-- (none defined)" >> "$OUTPUT_DIR/baseline.sql"
fi

# Append procedures section
cat >> "$OUTPUT_DIR/baseline.sql" << 'PROCEDURES_HEADER'

-- -----------------------------------------------------------------------------
-- STORED PROCEDURES
-- -----------------------------------------------------------------------------

PROCEDURES_HEADER

for PROC_FILE in "$OUTPUT_DIR"/procedures/*.sql; do
    if [[ -f "$PROC_FILE" ]]; then
        cat "$PROC_FILE" >> "$OUTPUT_DIR/baseline.sql"
        echo "" >> "$OUTPUT_DIR/baseline.sql"
    fi
done

if [[ ! -f "$OUTPUT_DIR"/procedures/*.sql ]]; then
    echo "-- (none defined)" >> "$OUTPUT_DIR/baseline.sql"
fi

# Append views section
cat >> "$OUTPUT_DIR/baseline.sql" << 'VIEWS_HEADER'

-- -----------------------------------------------------------------------------
-- VIEWS
-- -----------------------------------------------------------------------------

VIEWS_HEADER

for VIEW_FILE in "$OUTPUT_DIR"/views/*.sql; do
    if [[ -f "$VIEW_FILE" ]]; then
        cat "$VIEW_FILE" >> "$OUTPUT_DIR/baseline.sql"
        echo "" >> "$OUTPUT_DIR/baseline.sql"
    fi
done

if [[ ! -f "$OUTPUT_DIR"/views/*.sql ]]; then
    echo "-- (none defined)" >> "$OUTPUT_DIR/baseline.sql"
fi

# Footer
cat >> "$OUTPUT_DIR/baseline.sql" << 'FOOTER'

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- END OF BASELINE
-- =============================================================================
FOOTER

log_success "Schema generated successfully!"
echo ""
log_info "Output directory: $OUTPUT_DIR"
log_info "Baseline version: $BASELINE_VERSION"
echo ""
log_info "Files created:"
find "$OUTPUT_DIR" -name "*.sql" -type f | while read -r f; do
    echo "  - $f"
done
